language: go

go:
  - 1.8
  - master

sudo: required

services:
  - docker

script:
  - export MOCK= && go test -v ./cli/vendor/service
  - go test -v ./service/vendor/entities
  - docker build . -t agenda
  - docker run -dit --name service -p 8080:8080 -v /data:/data agenda service
  - docker run --rm --network host -v /data:/data agenda cli help
